version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile-web
    ports:
      - "8080:8080"
    depends_on:
      - app
    volumes:
      - public:/usr/app/public
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
      - public:/usr/app/public
    depends_on:
      - db
    environment:
      - DOCKER_DB_HOST=db
  db:
    image: "postgres:latest"
    environment:
      POSTGRES_DB: musicbox-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
volumes:
  public:
