version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile-web
    ports:
      - "8080:80"
    depends_on:
      - app
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    depends_on:
      - db
    environment:
      - DOCKER_DB_HOST=db
    ports:
  db:
    image: "postgres:latest"
    environment:
      POSTGRES_DB: musicbox-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      
